name: Update GitHub Stats SVG

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows you to run manually anytime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants permission to save the image to your repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Generate Stats Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=lightningMcQueen-95&show_icons=true&hide_border=true&bg_color=0D1117&title_color=A78BFA&icon_color=A78BFA&text_color=E2E8F0&count_private=true&rank_icon=github
          token: ${{ secrets.GITHUB_TOKEN }}
